import 'package:flutter/material.dart';

class Calls extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(decoration: BoxDecoration(color: Colors.cyan[100]),
      height: double.infinity, width: double.infinity,
      child: ListView(scrollDirection: Axis.vertical,
          children: <Widget>[SizedBox(height: 10),
            ListTile(onTap: () {},
              leading: Icon(Icons.call_made, size: 30, color: Colors.green,),
              title: Text('Elon', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
            SizedBox(height: 5),
            ListTile(onTap: () {},
              leading: Icon(Icons.call_made, size: 30, color: Colors.green,),
              title: Text('Elon', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
            SizedBox(height: 5),
            ListTile(onTap: () {},
              leading: Icon(Icons.call_missed, size: 30, color: Colors.redAccent,),
              title: Text('Elon', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
            SizedBox(height: 5),
            ListTile(onTap: () {},
              leading: Icon(Icons.call_received, size: 30, color: Colors.green,),
              title: Text('Rajshree', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
            SizedBox(height: 5),
            ListTile(onTap: () {},
              leading: Icon(Icons.call_made, size: 30, color: Colors.green),
              title: Text('Fatima', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
            SizedBox(height: 5),
            ListTile(onTap: () {},
              leading: Icon(Icons.call_received, size: 30, color: Colors.green),
              title: Text('Gracia', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
            SizedBox(height: 5),
            ListTile(onTap: () {},
              leading: Icon(Icons.call_missed_outgoing, size: 30, color: Colors.redAccent),
              title: Text('Gracia', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
            SizedBox(height: 5),
            ListTile(
              leading: Icon(Icons.call_received, size: 30, color: Colors.green,),
              title: Text('Natasha', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
            SizedBox(height: 5),
            ListTile(onTap: () {},
              leading: Icon(Icons.call_received, size: 30, color: Colors.green,),
              title: Text('Prince', style: TextStyle(fontSize: 17,
                  fontWeight: FontWeight.bold))),
          ]));
  }
}
