import 'package:chat_app/main.dart';
import 'package:flutter/material.dart';

class Groups extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(color: Colors.cyan[100]),
      height: double.infinity, width: double.infinity,
      child: ListView(scrollDirection: Axis.vertical,
        children: <Widget>[
          SizedBox(height: 20),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30, backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Anaaya', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
          SizedBox(height: 20,),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30, backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Andrea', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),

          SizedBox(height: 20),
          ListTile(onTap: () {}, leading: CircleAvatar(radius: 30,
              backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Bernadine', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
          SizedBox(height: 20,),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30,
              backgroundImage: AssetImage('images/elda.jpg')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Elda', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
          SizedBox(height: 10),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30,
              backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Maria', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
          SizedBox(height: 20),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30,
              backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Naira', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
          SizedBox(height: 20),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30, backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Peterson', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
          SizedBox(height: 20),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30, backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Priya', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
          SizedBox(height: 20),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30, backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Shreya', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
          SizedBox(height: 20),
          ListTile(onTap: () {},
            leading: CircleAvatar(radius: 30, backgroundImage: AssetImage('')),
            trailing: Icon(Icons.message, size: 35, color: PrimaryColor),
            title: Text('Ziaan', style: TextStyle(fontSize: 17,
                fontWeight: FontWeight.bold))),
        ]));
  }
}